name: Run Batch Script on Self-Hosted Runner

on:
#  push:
#    branches:
#      - main
  workflow_dispatch:

jobs:
  run-batch:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run batch script
      run: C:\batch_scripts\'example-script-demo.bat'
      shell: cmd
     # run: C:\batch_scripts\'example-script-demo.bat'
     # shell: cmd
  
